// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvofewtxpbbukfatlmyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2b2Zld3R4cGJidWtmYXRsbXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDY1MDAsImV4cCI6MjA2Mjg4MjUwMH0.IZfqv-QoA6fokRzUkUHYWW4uPmCYZPw0a-WdJQEM7b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);